-- Datos mínimos para ejecutar el backend en perfil dev con H2.
-- Password de usuarios semilla: Password123

INSERT INTO PLANES (NOMBRE, PANTALLAS_SIMULTANEAS, CALIDAD, PRECIO_MENSUAL, MAX_PERFILES, ACTIVO)
VALUES ('BASICO', 1, 'SD', 14900, 2, 'S');
INSERT INTO PLANES (NOMBRE, PANTALLAS_SIMULTANEAS, CALIDAD, PRECIO_MENSUAL, MAX_PERFILES, ACTIVO)
VALUES ('ESTANDAR', 2, 'HD', 24900, 3, 'S');
INSERT INTO PLANES (NOMBRE, PANTALLAS_SIMULTANEAS, CALIDAD, PRECIO_MENSUAL, MAX_PERFILES, ACTIVO)
VALUES ('PREMIUM', 4, '4K', 34900, 5, 'S');

INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Películas','PELICULA');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Series','SERIE');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Documentales','DOCUMENTAL');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Música','MUSICA');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Podcasts','PODCAST');

INSERT INTO GENEROS (NOMBRE) VALUES ('Acción');
INSERT INTO GENEROS (NOMBRE) VALUES ('Comedia');
INSERT INTO GENEROS (NOMBRE) VALUES ('Drama');
INSERT INTO GENEROS (NOMBRE) VALUES ('Suspenso');
INSERT INTO GENEROS (NOMBRE) VALUES ('Infantil');

INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('Contenido');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('Soporte');

INSERT INTO EMPLEADOS (NOMBRE, EMAIL, ID_DEPARTAMENTO, ID_SUPERVISOR, CARGO, ACTIVO)
VALUES ('Empleado Contenido', 'contenido@quindioflix.com', 1, NULL, 'Gestor de contenido', 'S');
INSERT INTO EMPLEADOS (NOMBRE, EMAIL, ID_DEPARTAMENTO, ID_SUPERVISOR, CARGO, ACTIVO)
VALUES ('Moderador Soporte', 'moderador@quindioflix.com', 2, NULL, 'Moderador', 'S');
UPDATE DEPARTAMENTOS SET ID_JEFE = 1 WHERE ID_DEPARTAMENTO = 1;
UPDATE DEPARTAMENTOS SET ID_JEFE = 2 WHERE ID_DEPARTAMENTO = 2;

INSERT INTO USUARIOS (NOMBRE, EMAIL, TELEFONO, FECHA_NACIMIENTO, CIUDAD, PASSWORD_HASH, ID_PLAN, ESTADO_CUENTA, FECHA_REGISTRO, FECHA_ULTIMO_PAGO, FECHA_VENCIMIENTO, ID_REFERIDO_POR, ROL)
VALUES ('Usuario Admin', 'usuario1@mail.com', '3000000001', DATE '1999-01-01', 'Armenia', '$2a$10$wuJIc0U/OAbjduBxAsERZOpE.G73uVWHuKDNSSsVVC7GfA0BpJ1km', 3, 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, DATEADD('DAY', 30, CURRENT_TIMESTAMP), NULL, 'ADMIN');
INSERT INTO USUARIOS (NOMBRE, EMAIL, TELEFONO, FECHA_NACIMIENTO, CIUDAD, PASSWORD_HASH, ID_PLAN, ESTADO_CUENTA, FECHA_REGISTRO, FECHA_ULTIMO_PAGO, FECHA_VENCIMIENTO, ID_REFERIDO_POR, ROL)
VALUES ('Usuario Moderador', 'usuario2@mail.com', '3000000002', DATE '1998-01-01', 'Armenia', '$2a$10$wuJIc0U/OAbjduBxAsERZOpE.G73uVWHuKDNSSsVVC7GfA0BpJ1km', 2, 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, DATEADD('DAY', 30, CURRENT_TIMESTAMP), NULL, 'MODERADOR');
INSERT INTO USUARIOS (NOMBRE, EMAIL, TELEFONO, FECHA_NACIMIENTO, CIUDAD, PASSWORD_HASH, ID_PLAN, ESTADO_CUENTA, FECHA_REGISTRO, FECHA_ULTIMO_PAGO, FECHA_VENCIMIENTO, ID_REFERIDO_POR, ROL)
VALUES ('Usuario Contenido', 'usuario3@mail.com', '3000000003', DATE '1997-01-01', 'Armenia', '$2a$10$wuJIc0U/OAbjduBxAsERZOpE.G73uVWHuKDNSSsVVC7GfA0BpJ1km', 2, 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, DATEADD('DAY', 30, CURRENT_TIMESTAMP), NULL, 'CONTENIDO');
INSERT INTO USUARIOS (NOMBRE, EMAIL, TELEFONO, FECHA_NACIMIENTO, CIUDAD, PASSWORD_HASH, ID_PLAN, ESTADO_CUENTA, FECHA_REGISTRO, FECHA_ULTIMO_PAGO, FECHA_VENCIMIENTO, ID_REFERIDO_POR, ROL)
VALUES ('Usuario Cliente', 'usuario4@mail.com', '3000000004', DATE '1996-01-01', 'Cali', '$2a$10$wuJIc0U/OAbjduBxAsERZOpE.G73uVWHuKDNSSsVVC7GfA0BpJ1km', 1, 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, DATEADD('DAY', 30, CURRENT_TIMESTAMP), 1, 'CLIENTE');

INSERT INTO PERFILES (ID_USUARIO, NOMBRE, AVATAR, TIPO_PERFIL) VALUES (1, 'Principal', 'avatar-admin.png', 'ADULTO');
INSERT INTO PERFILES (ID_USUARIO, NOMBRE, AVATAR, TIPO_PERFIL) VALUES (2, 'Principal', 'avatar-mod.png', 'ADULTO');
INSERT INTO PERFILES (ID_USUARIO, NOMBRE, AVATAR, TIPO_PERFIL) VALUES (3, 'Principal', 'avatar-cont.png', 'ADULTO');
INSERT INTO PERFILES (ID_USUARIO, NOMBRE, AVATAR, TIPO_PERFIL) VALUES (4, 'Principal', 'avatar-cli.png', 'ADULTO');

INSERT INTO CONTENIDO (ID_CATEGORIA, TITULO, ANIO_LANZAMIENTO, DURACION_MINUTOS, SINOPSIS, CLASIFICACION_EDAD, FECHA_AGREGADO, ORIGINAL_QUINDIOFLIX, ID_EMPLEADO_RESPONSABLE, POPULARIDAD)
VALUES (1, 'Película de prueba', 2025, 120, 'Contenido base para pruebas locales.', 'MAS_13', CURRENT_DATE, 'S', 1, 0);
INSERT INTO CONTENIDO (ID_CATEGORIA, TITULO, ANIO_LANZAMIENTO, DURACION_MINUTOS, SINOPSIS, CLASIFICACION_EDAD, FECHA_AGREGADO, ORIGINAL_QUINDIOFLIX, ID_EMPLEADO_RESPONSABLE, POPULARIDAD)
VALUES (2, 'Serie de prueba', 2025, 45, 'Serie base para pruebas locales.', 'MAS_13', CURRENT_DATE, 'S', 1, 0);
INSERT INTO CONTENIDO_GENERO (ID_CONTENIDO, ID_GENERO) VALUES (1, 1);
INSERT INTO CONTENIDO_GENERO (ID_CONTENIDO, ID_GENERO) VALUES (2, 3);

INSERT INTO TEMPORADAS (ID_CONTENIDO, NUMERO_TEMPORADA, TITULO, FECHA_LANZAMIENTO)
VALUES (2, 1, 'Temporada 1', CURRENT_DATE);
INSERT INTO EPISODIOS (ID_TEMPORADA, NUMERO_EPISODIO, TITULO, DURACION_MINUTOS, SINOPSIS)
VALUES (1, 1, 'Episodio 1', 45, 'Primer episodio de prueba.');

INSERT INTO PAGOS (ID_USUARIO, FECHA_PAGO, MONTO, METODO_PAGO, ESTADO_PAGO, REFERENCIA, DESCUENTO_APLICADO)
VALUES (1, CURRENT_TIMESTAMP, 34900, 'PSE', 'EXITOSO', 'DEV-ADMIN', 0);
INSERT INTO PAGOS (ID_USUARIO, FECHA_PAGO, MONTO, METODO_PAGO, ESTADO_PAGO, REFERENCIA, DESCUENTO_APLICADO)
VALUES (4, CURRENT_TIMESTAMP, 13410, 'PSE', 'EXITOSO', 'DEV-CLIENTE', 1490);
