-- 00_crear_usuario_app.sql
-- Ejecutar como SYS/SYSTEM en la PDB que usarás desde SQL Developer.
-- Ajusta la contraseña si lo deseas.

CREATE USER QUINDIOFLIX_APP IDENTIFIED BY QuindioFlix_2026;
GRANT CREATE SESSION TO QUINDIOFLIX_APP;
GRANT CREATE TABLE TO QUINDIOFLIX_APP;
GRANT CREATE VIEW TO QUINDIOFLIX_APP;
GRANT CREATE MATERIALIZED VIEW TO QUINDIOFLIX_APP;
GRANT CREATE PROCEDURE TO QUINDIOFLIX_APP;
GRANT CREATE TRIGGER TO QUINDIOFLIX_APP;
GRANT CREATE SEQUENCE TO QUINDIOFLIX_APP;
GRANT UNLIMITED TABLESPACE TO QUINDIOFLIX_APP;
