-- V2__seed_data.sql
-- Datos asimétricos para reportes de PIVOT, ROLLUP, CUBE y analítica.
-- Password de los usuarios semilla: Password123

INSERT INTO PLANES (NOMBRE, PANTALLAS_SIMULTANEAS, CALIDAD, PRECIO_MENSUAL, MAX_PERFILES, ACTIVO) VALUES ('BASICO', 1, 'SD', 14900, 2, 'S');
INSERT INTO PLANES (NOMBRE, PANTALLAS_SIMULTANEAS, CALIDAD, PRECIO_MENSUAL, MAX_PERFILES, ACTIVO) VALUES ('ESTANDAR', 2, 'HD', 24900, 3, 'S');
INSERT INTO PLANES (NOMBRE, PANTALLAS_SIMULTANEAS, CALIDAD, PRECIO_MENSUAL, MAX_PERFILES, ACTIVO) VALUES ('PREMIUM', 4, '4K', 34900, 5, 'S');

INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Películas','PELICULA');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Series','SERIE');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Documentales','DOCUMENTAL');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Música','MUSICA');
INSERT INTO CATEGORIAS (NOMBRE, TIPO_CONTENIDO) VALUES ('Podcasts','PODCAST');

INSERT INTO GENEROS (NOMBRE) VALUES ('Acción');
INSERT INTO GENEROS (NOMBRE) VALUES ('Comedia');
INSERT INTO GENEROS (NOMBRE) VALUES ('Drama');
INSERT INTO GENEROS (NOMBRE) VALUES ('Suspenso');
INSERT INTO GENEROS (NOMBRE) VALUES ('Romance');
INSERT INTO GENEROS (NOMBRE) VALUES ('Ciencia Ficción');
INSERT INTO GENEROS (NOMBRE) VALUES ('Terror');
INSERT INTO GENEROS (NOMBRE) VALUES ('Infantil');

INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('Tecnología');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('Contenido');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('Marketing');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('Soporte');
INSERT INTO DEPARTAMENTOS (NOMBRE) VALUES ('Finanzas');

BEGIN
  FOR i IN 1..10 LOOP
    INSERT INTO EMPLEADOS (NOMBRE, EMAIL, ID_DEPARTAMENTO, ID_SUPERVISOR, CARGO, ACTIVO)
    VALUES ('Empleado '||i, 'empleado'||i||'@quindioflix.com', MOD(i-1,5)+1, CASE WHEN i>5 THEN MOD(i-1,5)+1 ELSE NULL END,
            CASE WHEN MOD(i,5)=2 THEN 'Gestor de contenido' WHEN MOD(i,5)=4 THEN 'Analista soporte' ELSE 'Profesional' END, 'S');
  END LOOP;
  UPDATE DEPARTAMENTOS SET ID_JEFE = (SELECT MIN(e.ID_EMPLEADO) FROM EMPLEADOS e WHERE e.ID_DEPARTAMENTO = DEPARTAMENTOS.ID_DEPARTAMENTO);
END;
/

DECLARE
  v_hash VARCHAR2(255) := '$2a$10$wuJIc0U/OAbjduBxAsERZOpE.G73uVWHuKDNSSsVVC7GfA0BpJ1km';
BEGIN
  FOR i IN 1..30 LOOP
    INSERT INTO USUARIOS (NOMBRE, EMAIL, TELEFONO, FECHA_NACIMIENTO, CIUDAD, PASSWORD_HASH, ID_PLAN, ESTADO_CUENTA, FECHA_REGISTRO, FECHA_ULTIMO_PAGO, FECHA_VENCIMIENTO, ID_REFERIDO_POR, ROL)
    VALUES ('Usuario '||i, 'usuario'||i||'@mail.com', '30000000'||LPAD(i,2,'0'), ADD_MONTHS(DATE '2000-01-01', -12*i),
            CASE WHEN MOD(i,4)=0 THEN 'Bogotá' WHEN MOD(i,4)=1 THEN 'Armenia' WHEN MOD(i,4)=2 THEN 'Cali' ELSE 'Medellín' END,
            v_hash, MOD(i-1,3)+1, CASE WHEN MOD(i,13)=0 THEN 'INACTIVO' ELSE 'ACTIVO' END,
            ADD_MONTHS(SYSTIMESTAMP, -MOD(i,30)), SYSTIMESTAMP - NUMTODSINTERVAL(MOD(i,45),'DAY'),
            SYSTIMESTAMP + NUMTODSINTERVAL(30 - MOD(i,45),'DAY'), CASE WHEN i>5 AND MOD(i,5)=0 THEN i-5 ELSE NULL END,
            CASE WHEN i=1 THEN 'ADMIN' WHEN i=2 THEN 'MODERADOR' WHEN i=3 THEN 'CONTENIDO' ELSE 'CLIENTE' END);
  END LOOP;

  FOR i IN 1..50 LOOP
    INSERT INTO PERFILES (ID_USUARIO, NOMBRE, AVATAR, TIPO_PERFIL)
    VALUES (MOD(i-1,30)+1, 'Perfil '||i, 'avatar'||MOD(i,8)||'.png', CASE WHEN MOD(i,5)=0 THEN 'INFANTIL' ELSE 'ADULTO' END);
  END LOOP;

  FOR i IN 1..40 LOOP
    INSERT INTO CONTENIDO (ID_CATEGORIA, TITULO, ANIO_LANZAMIENTO, DURACION_MINUTOS, SINOPSIS, CLASIFICACION_EDAD, FECHA_AGREGADO, ORIGINAL_QUINDIOFLIX, ID_EMPLEADO_RESPONSABLE, POPULARIDAD)
    VALUES (MOD(i-1,5)+1, 'Contenido QuindioFlix '||i, 2010+MOD(i,16), 30+MOD(i*7,120), 'Sinopsis del contenido '||i,
            CASE MOD(i,5) WHEN 0 THEN 'TP' WHEN 1 THEN 'MAS_7' WHEN 2 THEN 'MAS_13' WHEN 3 THEN 'MAS_16' ELSE 'MAS_18' END,
            SYSDATE - MOD(i,900), CASE WHEN MOD(i,4)=0 THEN 'S' ELSE 'N' END, MOD(i-1,10)+1, 0);
    INSERT INTO CONTENIDO_GENERO (ID_CONTENIDO, ID_GENERO) VALUES (i, MOD(i-1,8)+1);
    INSERT INTO CONTENIDO_GENERO (ID_CONTENIDO, ID_GENERO) VALUES (i, MOD(i+2,8)+1);
  END LOOP;

  FOR i IN 1..8 LOOP
    INSERT INTO TEMPORADAS (ID_CONTENIDO, NUMERO_TEMPORADA, TITULO, FECHA_LANZAMIENTO) VALUES ((i-1)*5+2, 1, 'Temporada serie '||i, SYSDATE - i*30);
  END LOOP;
  FOR i IN 1..7 LOOP
    INSERT INTO TEMPORADAS (ID_CONTENIDO, NUMERO_TEMPORADA, TITULO, FECHA_LANZAMIENTO) VALUES ((i-1)*5+5, 1, 'Temporada podcast '||i, SYSDATE - i*25);
  END LOOP;

  FOR i IN 1..50 LOOP
    INSERT INTO EPISODIOS (ID_TEMPORADA, NUMERO_EPISODIO, TITULO, DURACION_MINUTOS, SINOPSIS)
    VALUES (MOD(i-1,15)+1, CEIL(i/15), 'Episodio '||i, 20+MOD(i,50), 'Sinopsis episodio '||i);
  END LOOP;

  FOR i IN 1..10 LOOP
    INSERT INTO CONTENIDO_RELACIONADO (ID_CONTENIDO_ORIGEN, ID_CONTENIDO_DESTINO, TIPO_RELACION, DESCRIPCION)
    VALUES (i, i+10, CASE WHEN MOD(i,2)=0 THEN 'SECUELA' ELSE 'SPIN_OFF' END, 'Relación editorial entre contenidos');
  END LOOP;

  FOR i IN 1..200 LOOP
    INSERT INTO REPRODUCCIONES (ID_PERFIL, ID_CONTENIDO, ID_EPISODIO, FECHA_HORA_INICIO, FECHA_HORA_FIN, DISPOSITIVO, PORCENTAJE_AVANCE)
    VALUES (MOD(i-1,50)+1, MOD(i-1,40)+1, CASE WHEN MOD(i,3)=0 THEN MOD(i-1,50)+1 ELSE NULL END,
            SYSTIMESTAMP - NUMTODSINTERVAL(MOD(i,730),'DAY'), SYSTIMESTAMP - NUMTODSINTERVAL(MOD(i,730),'DAY') + NUMTODSINTERVAL(30+MOD(i,90),'MINUTE'),
            CASE MOD(i,4) WHEN 0 THEN 'CELULAR' WHEN 1 THEN 'TABLET' WHEN 2 THEN 'TV' ELSE 'COMPUTADOR' END, MOD(i*13,101));
  END LOOP;

  FOR i IN 1..60 LOOP
    INSERT INTO CALIFICACIONES (ID_PERFIL, ID_CONTENIDO, ESTRELLAS, RESENA, FECHA_CALIFICACION)
    VALUES (MOD(i-1,50)+1, MOD(i*7,40)+1, MOD(i,5)+1, 'Reseña automática '||i, SYSTIMESTAMP - NUMTODSINTERVAL(i,'DAY'));
  END LOOP;

  FOR i IN 1..40 LOOP
    INSERT INTO FAVORITOS (ID_PERFIL, ID_CONTENIDO, FECHA_AGREGADO)
    VALUES (MOD(i-1,50)+1, MOD(i*9,40)+1, SYSTIMESTAMP - NUMTODSINTERVAL(i,'DAY'));
  END LOOP;

  FOR i IN 1..80 LOOP
    INSERT INTO PAGOS (ID_USUARIO, FECHA_PAGO, MONTO, METODO_PAGO, ESTADO_PAGO, REFERENCIA, DESCUENTO_APLICADO)
    VALUES (MOD(i-1,30)+1, ADD_MONTHS(SYSTIMESTAMP, -MOD(i,8)), CASE MOD(i,3) WHEN 0 THEN 14900 WHEN 1 THEN 24900 ELSE 34900 END,
            CASE MOD(i,5) WHEN 0 THEN 'TARJETA_CREDITO' WHEN 1 THEN 'TARJETA_DEBITO' WHEN 2 THEN 'PSE' WHEN 3 THEN 'NEQUI' ELSE 'DAVIPLATA' END,
            CASE WHEN MOD(i,10)=0 THEN 'FALLIDO' WHEN MOD(i,15)=0 THEN 'PENDIENTE' ELSE 'EXITOSO' END,
            'REF-'||TO_CHAR(i), CASE WHEN MOD(i,12)=0 THEN 3000 ELSE 0 END);
  END LOOP;
END;
/

COMMIT;
