-- 03_consultas_avanzadas.sql
-- Núcleo 1: consultas parametrizadas, PIVOT, UNPIVOT, ROLLUP, CUBE, GROUPING SETS,
-- vistas materializadas y fragmentación lógica por rango de fechas.

-- 1) Consulta parametrizada: top 10 de contenido más reproducido por ciudad.
DEFINE p_ciudad = 'Armenia';
SELECT * FROM (
  SELECT c.TITULO, COUNT(*) TOTAL_REPRODUCCIONES
  FROM REPRODUCCIONES r
  JOIN PERFILES p ON p.ID_PERFIL = r.ID_PERFIL
  JOIN USUARIOS u ON u.ID_USUARIO = p.ID_USUARIO
  JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
  WHERE UPPER(u.CIUDAD) = UPPER('&p_ciudad')
  GROUP BY c.TITULO
  ORDER BY TOTAL_REPRODUCCIONES DESC
) WHERE ROWNUM <= 10;

-- 2) Consulta parametrizada: ingresos por plan en mes y año.
DEFINE p_mes = 5;
DEFINE p_anio = 2026;
SELECT pl.NOMBRE PLAN, SUM(pa.MONTO) INGRESOS
FROM PAGOS pa
JOIN USUARIOS u ON u.ID_USUARIO = pa.ID_USUARIO
JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN
WHERE pa.ESTADO_PAGO = 'EXITOSO'
  AND EXTRACT(MONTH FROM pa.FECHA_PAGO) = &p_mes
  AND EXTRACT(YEAR FROM pa.FECHA_PAGO) = &p_anio
GROUP BY pl.NOMBRE;

-- 3) Consulta parametrizada: calificación promedio por categoría para un género.
DEFINE p_genero = 'Drama';
SELECT ca.NOMBRE CATEGORIA, ROUND(AVG(cal.ESTRELLAS),2) PROMEDIO
FROM CALIFICACIONES cal
JOIN CONTENIDO c ON c.ID_CONTENIDO = cal.ID_CONTENIDO
JOIN CATEGORIAS ca ON ca.ID_CATEGORIA = c.ID_CATEGORIA
JOIN CONTENIDO_GENERO cg ON cg.ID_CONTENIDO = c.ID_CONTENIDO
JOIN GENEROS g ON g.ID_GENERO = cg.ID_GENERO
WHERE UPPER(g.NOMBRE) = UPPER('&p_genero')
GROUP BY ca.NOMBRE;

-- PIVOT 1: usuarios activos por ciudad y plan.
SELECT * FROM (
  SELECT u.CIUDAD, pl.NOMBRE PLAN
  FROM USUARIOS u JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN
  WHERE u.ESTADO_CUENTA = 'ACTIVO'
) PIVOT (COUNT(*) FOR PLAN IN ('BASICO' AS BASICO, 'ESTANDAR' AS ESTANDAR, 'PREMIUM' AS PREMIUM));

-- PIVOT 2: reproducciones por categoría y dispositivo.
SELECT * FROM (
  SELECT ca.NOMBRE CATEGORIA, r.DISPOSITIVO
  FROM REPRODUCCIONES r
  JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
  JOIN CATEGORIAS ca ON ca.ID_CATEGORIA = c.ID_CATEGORIA
) PIVOT (COUNT(*) FOR DISPOSITIVO IN ('CELULAR' AS CELULAR, 'TABLET' AS TABLET, 'TV' AS TV, 'COMPUTADOR' AS COMPUTADOR));

-- UNPIVOT 1: volver a filas un reporte de usuarios por plan.
WITH reporte AS (
  SELECT * FROM (
    SELECT u.CIUDAD, pl.NOMBRE PLAN FROM USUARIOS u JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN
  ) PIVOT (COUNT(*) FOR PLAN IN ('BASICO' AS BASICO, 'ESTANDAR' AS ESTANDAR, 'PREMIUM' AS PREMIUM))
)
SELECT CIUDAD, PLAN, TOTAL_USUARIOS
FROM reporte
UNPIVOT (TOTAL_USUARIOS FOR PLAN IN (BASICO AS 'BASICO', ESTANDAR AS 'ESTANDAR', PREMIUM AS 'PREMIUM'));

-- UNPIVOT 2: meses como columnas a filas.
WITH resumen_meses AS (
  SELECT 'Ingresos' METRICA, 1000000 ENERO, 1200000 FEBRERO, 950000 MARZO FROM DUAL
)
SELECT METRICA, MES, VALOR
FROM resumen_meses
UNPIVOT (VALOR FOR MES IN (ENERO AS 'ENERO', FEBRERO AS 'FEBRERO', MARZO AS 'MARZO'));

-- ROLLUP + GROUPING: ingresos por ciudad y plan con subtotales y total.
SELECT CASE WHEN GROUPING(u.CIUDAD)=1 THEN 'TOTAL GENERAL' ELSE u.CIUDAD END CIUDAD,
       CASE WHEN GROUPING(pl.NOMBRE)=1 THEN 'SUBTOTAL CIUDAD' ELSE pl.NOMBRE END PLAN,
       SUM(pa.MONTO) INGRESOS
FROM PAGOS pa
JOIN USUARIOS u ON u.ID_USUARIO = pa.ID_USUARIO
JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN
WHERE pa.ESTADO_PAGO = 'EXITOSO'
GROUP BY ROLLUP(u.CIUDAD, pl.NOMBRE);

-- CUBE: reproducciones por categoría y dispositivo con todas las combinaciones.
SELECT CASE WHEN GROUPING(ca.NOMBRE)=1 THEN 'TODAS LAS CATEGORIAS' ELSE ca.NOMBRE END CATEGORIA,
       CASE WHEN GROUPING(r.DISPOSITIVO)=1 THEN 'TODOS LOS DISPOSITIVOS' ELSE r.DISPOSITIVO END DISPOSITIVO,
       COUNT(*) TOTAL
FROM REPRODUCCIONES r
JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
JOIN CATEGORIAS ca ON ca.ID_CATEGORIA = c.ID_CATEGORIA
GROUP BY CUBE(ca.NOMBRE, r.DISPOSITIVO);

-- GROUPING SETS: solo totales por categoría y ciudad, sin detalle cruzado.
SELECT ca.NOMBRE CATEGORIA, u.CIUDAD, COUNT(*) TOTAL
FROM REPRODUCCIONES r
JOIN PERFILES p ON p.ID_PERFIL = r.ID_PERFIL
JOIN USUARIOS u ON u.ID_USUARIO = p.ID_USUARIO
JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
JOIN CATEGORIAS ca ON ca.ID_CATEGORIA = c.ID_CATEGORIA
GROUP BY GROUPING SETS ((ca.NOMBRE), (u.CIUDAD));

-- Vistas materializadas.
CREATE MATERIALIZED VIEW MV_CONTENIDO_POPULAR
BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT c.ID_CONTENIDO, c.TITULO, COUNT(r.ID_REPRODUCCION) TOTAL_REPRODUCCIONES,
       ROUND(AVG(cal.ESTRELLAS),2) CALIFICACION_PROMEDIO
FROM CONTENIDO c
LEFT JOIN REPRODUCCIONES r ON r.ID_CONTENIDO = c.ID_CONTENIDO
LEFT JOIN CALIFICACIONES cal ON cal.ID_CONTENIDO = c.ID_CONTENIDO
GROUP BY c.ID_CONTENIDO, c.TITULO;

CREATE MATERIALIZED VIEW MV_INGRESOS_MENSUALES
BUILD IMMEDIATE REFRESH COMPLETE ON DEMAND AS
SELECT EXTRACT(YEAR FROM pa.FECHA_PAGO) ANIO, EXTRACT(MONTH FROM pa.FECHA_PAGO) MES,
       u.CIUDAD, pl.NOMBRE PLAN, SUM(pa.MONTO) INGRESOS
FROM PAGOS pa
JOIN USUARIOS u ON u.ID_USUARIO = pa.ID_USUARIO
JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN
WHERE pa.ESTADO_PAGO = 'EXITOSO'
GROUP BY EXTRACT(YEAR FROM pa.FECHA_PAGO), EXTRACT(MONTH FROM pa.FECHA_PAGO), u.CIUDAD, pl.NOMBRE;


-- Verificación de vistas materializadas exigidas.
SELECT MVIEW_NAME, BUILD_MODE, REFRESH_METHOD, REFRESH_MODE
FROM USER_MVIEWS
WHERE MVIEW_NAME IN ('MV_CONTENIDO_POPULAR', 'MV_INGRESOS_MENSUALES')
ORDER BY MVIEW_NAME;

-- Refresco manual de vistas materializadas para evidencias.
BEGIN
  DBMS_MVIEW.REFRESH('MV_CONTENIDO_POPULAR', 'C');
  DBMS_MVIEW.REFRESH('MV_INGRESOS_MENSUALES', 'C');
END;
/

-- 3.1.5 Fragmentación física por rango de fechas con tablespaces.
-- Ejecutar este bloque con un usuario DBA o con privilegio CREATE TABLESPACE.
-- Si tu Oracle no permite rutas relativas para DATAFILE, cambia los nombres por rutas absolutas válidas.
CREATE TABLESPACE TS_REP_2024 DATAFILE 'ts_rep_2024.dbf' SIZE 100M AUTOEXTEND ON NEXT 20M MAXSIZE 500M;
CREATE TABLESPACE TS_REP_2025 DATAFILE 'ts_rep_2025.dbf' SIZE 100M AUTOEXTEND ON NEXT 20M MAXSIZE 500M;
CREATE TABLESPACE TS_REP_FUTURO DATAFILE 'ts_rep_futuro.dbf' SIZE 100M AUTOEXTEND ON NEXT 20M MAXSIZE 500M;

-- Tabla fragmentada para evidenciar la estrategia sin destruir la tabla operacional REPRODUCCIONES.
-- Se usa el mismo diseño lógico y se particiona por FECHA_HORA_INICIO.
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE REPRODUCCIONES_FRAGMENTADA PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE REPRODUCCIONES_FRAGMENTADA (
  ID_REPRODUCCION NUMBER(19,0),
  ID_PERFIL NUMBER(19,0) NOT NULL,
  ID_CONTENIDO NUMBER(19,0) NOT NULL,
  ID_EPISODIO NUMBER(19,0),
  FECHA_HORA_INICIO TIMESTAMP NOT NULL,
  FECHA_HORA_FIN TIMESTAMP,
  DISPOSITIVO VARCHAR2(20) NOT NULL,
  PORCENTAJE_AVANCE NUMBER(3) NOT NULL
)
PARTITION BY RANGE (FECHA_HORA_INICIO) (
  PARTITION REP_2024 VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00') TABLESPACE TS_REP_2024,
  PARTITION REP_2025 VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00') TABLESPACE TS_REP_2025,
  PARTITION REP_FUTURO VALUES LESS THAN (MAXVALUE) TABLESPACE TS_REP_FUTURO
);

INSERT INTO REPRODUCCIONES_FRAGMENTADA (
  ID_REPRODUCCION, ID_PERFIL, ID_CONTENIDO, ID_EPISODIO, FECHA_HORA_INICIO,
  FECHA_HORA_FIN, DISPOSITIVO, PORCENTAJE_AVANCE
)
SELECT ID_REPRODUCCION, ID_PERFIL, ID_CONTENIDO, ID_EPISODIO, FECHA_HORA_INICIO,
       FECHA_HORA_FIN, DISPOSITIVO, PORCENTAJE_AVANCE
FROM REPRODUCCIONES;

COMMIT;

SELECT TABLE_NAME, PARTITION_NAME, TABLESPACE_NAME, HIGH_VALUE
FROM USER_TAB_PARTITIONS
WHERE TABLE_NAME = 'REPRODUCCIONES_FRAGMENTADA'
ORDER BY PARTITION_POSITION;
