-- 04_plsql.sql
-- Núcleo 2: cursores, procedimientos, funciones, excepciones y disparadores.

CREATE OR REPLACE PROCEDURE SP_REPORTE_USUARIOS_VENCIDOS AS
  CURSOR c_vencidos IS
    SELECT u.NOMBRE, u.EMAIL, pl.NOMBRE PLAN, TRUNC(SYSDATE - CAST(u.FECHA_ULTIMO_PAGO AS DATE)) DIAS_MORA, pl.PRECIO_MENSUAL MONTO
    FROM USUARIOS u JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN
    WHERE u.FECHA_ULTIMO_PAGO < SYSTIMESTAMP - INTERVAL '30' DAY;
BEGIN
  FOR r IN c_vencidos LOOP
    DBMS_OUTPUT.PUT_LINE(r.NOMBRE || ' - ' || r.EMAIL || ' - ' || r.PLAN || ' - mora: ' || r.DIAS_MORA || ' días - $' || r.MONTO);
  END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_POPULARIDAD AS
  CURSOR c_contenido IS SELECT ID_CONTENIDO FROM CONTENIDO;
  v_total NUMBER;
BEGIN
  FOR c IN c_contenido LOOP
    SELECT COUNT(*) INTO v_total FROM REPRODUCCIONES WHERE ID_CONTENIDO = c.ID_CONTENIDO AND PORCENTAJE_AVANCE >= 90;
    UPDATE CONTENIDO SET POPULARIDAD = v_total WHERE ID_CONTENIDO = c.ID_CONTENIDO;
  END LOOP;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_USUARIO(
  p_nombre IN VARCHAR2, p_email IN VARCHAR2, p_telefono IN VARCHAR2, p_fecha_nacimiento IN DATE,
  p_ciudad IN VARCHAR2, p_password_hash IN VARCHAR2, p_id_plan IN NUMBER, p_metodo_pago IN VARCHAR2,
  p_monto IN NUMBER, p_id_usuario OUT NUMBER
) AS
  v_plan PLANES%ROWTYPE;
  ex_email_duplicado EXCEPTION;
  PRAGMA EXCEPTION_INIT(ex_email_duplicado, -20001);
BEGIN
  SELECT * INTO v_plan FROM PLANES WHERE ID_PLAN = p_id_plan AND ACTIVO = 'S';
  DECLARE
    v_email_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_email_count FROM USUARIOS WHERE LOWER(EMAIL) = LOWER(p_email);
    IF v_email_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'El email ya existe.');
    END IF;
  END;
  INSERT INTO USUARIOS (NOMBRE, EMAIL, TELEFONO, FECHA_NACIMIENTO, CIUDAD, PASSWORD_HASH, ID_PLAN, ESTADO_CUENTA, FECHA_REGISTRO, FECHA_ULTIMO_PAGO, FECHA_VENCIMIENTO, ROL)
  VALUES (p_nombre, LOWER(p_email), p_telefono, p_fecha_nacimiento, p_ciudad, p_password_hash, p_id_plan, 'ACTIVO', SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '30' DAY, 'CLIENTE')
  RETURNING ID_USUARIO INTO p_id_usuario;
  INSERT INTO PERFILES (ID_USUARIO, NOMBRE, AVATAR, TIPO_PERFIL) VALUES (p_id_usuario, 'Principal', 'avatar-default.png', 'ADULTO');
  INSERT INTO PAGOS (ID_USUARIO, FECHA_PAGO, MONTO, METODO_PAGO, ESTADO_PAGO, REFERENCIA, DESCUENTO_APLICADO)
  VALUES (p_id_usuario, SYSTIMESTAMP, p_monto, p_metodo_pago, 'EXITOSO', 'PAGO-INICIAL-SP', 0);
  COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN ROLLBACK; RAISE_APPLICATION_ERROR(-20002, 'El plan no existe o no está activo.');
  WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_CAMBIAR_PLAN(p_id_usuario IN NUMBER, p_id_plan_nuevo IN NUMBER) AS
  v_perfiles NUMBER; v_max NUMBER; v_plan_anterior NUMBER;
BEGIN
  SELECT ID_PLAN INTO v_plan_anterior FROM USUARIOS WHERE ID_USUARIO = p_id_usuario FOR UPDATE;
  SELECT MAX_PERFILES INTO v_max FROM PLANES WHERE ID_PLAN = p_id_plan_nuevo AND ACTIVO = 'S';
  SELECT COUNT(*) INTO v_perfiles FROM PERFILES WHERE ID_USUARIO = p_id_usuario;
  IF v_perfiles > v_max THEN
    RAISE_APPLICATION_ERROR(-20003, 'El usuario tiene más perfiles de los permitidos por el nuevo plan.');
  END IF;
  UPDATE USUARIOS SET ID_PLAN = p_id_plan_nuevo WHERE ID_USUARIO = p_id_usuario;
  INSERT INTO CAMBIOS_PLAN (ID_USUARIO, ID_PLAN_ANTERIOR, ID_PLAN_NUEVO, FECHA_CAMBIO, MOTIVO)
  VALUES (p_id_usuario, v_plan_anterior, p_id_plan_nuevo, SYSTIMESTAMP, 'Cambio por SP');
  COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE SP_REPORTE_CONSUMO(p_id_usuario IN NUMBER, p_desde IN DATE, p_hasta IN DATE, p_cursor OUT SYS_REFCURSOR) AS
BEGIN
  OPEN p_cursor FOR
    SELECT p.NOMBRE PERFIL, ca.NOMBRE CATEGORIA, COUNT(*) REPRODUCCIONES,
           SUM(c.DURACION_MINUTOS * r.PORCENTAJE_AVANCE / 100) MINUTOS_CONSUMIDOS
    FROM REPRODUCCIONES r
    JOIN PERFILES p ON p.ID_PERFIL = r.ID_PERFIL
    JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
    JOIN CATEGORIAS ca ON ca.ID_CATEGORIA = c.ID_CATEGORIA
    WHERE p.ID_USUARIO = p_id_usuario
      AND CAST(r.FECHA_HORA_INICIO AS DATE) BETWEEN p_desde AND p_hasta
    GROUP BY p.NOMBRE, ca.NOMBRE;
END;
/

CREATE OR REPLACE FUNCTION FN_CALCULAR_MONTO(p_id_usuario IN NUMBER) RETURN NUMBER AS
  v_precio NUMBER; v_meses NUMBER; v_monto NUMBER;
BEGIN
  SELECT pl.PRECIO_MENSUAL, MONTHS_BETWEEN(SYSDATE, CAST(u.FECHA_REGISTRO AS DATE))
  INTO v_precio, v_meses
  FROM USUARIOS u JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN
  WHERE u.ID_USUARIO = p_id_usuario;
  v_monto := CASE WHEN v_meses > 24 THEN v_precio * 0.85 WHEN v_meses > 12 THEN v_precio * 0.90 ELSE v_precio END;
  RETURN v_monto;
END;
/

CREATE OR REPLACE FUNCTION FN_CONTENIDO_RECOMENDADO(p_id_perfil IN NUMBER) RETURN VARCHAR2 AS
  v_titulo CONTENIDO.TITULO%TYPE;
BEGIN
  SELECT titulo INTO v_titulo FROM (
    SELECT c.TITULO, COUNT(*) afinidad
    FROM CONTENIDO c
    JOIN CONTENIDO_GENERO cg ON cg.ID_CONTENIDO = c.ID_CONTENIDO
    WHERE cg.ID_GENERO IN (
      SELECT ID_GENERO FROM (
        SELECT cg2.ID_GENERO, COUNT(*) total
        FROM REPRODUCCIONES r JOIN CONTENIDO_GENERO cg2 ON cg2.ID_CONTENIDO = r.ID_CONTENIDO
        WHERE r.ID_PERFIL = p_id_perfil
        GROUP BY cg2.ID_GENERO ORDER BY total DESC
      ) WHERE ROWNUM <= 3
    )
    AND c.ID_CONTENIDO NOT IN (SELECT ID_CONTENIDO FROM REPRODUCCIONES WHERE ID_PERFIL = p_id_perfil)
    GROUP BY c.TITULO ORDER BY afinidad DESC
  ) WHERE ROWNUM = 1;
  RETURN v_titulo;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN 'Sin recomendación disponible';
END;
/

CREATE OR REPLACE TRIGGER TRG_REP_CUENTA_ACTIVA
BEFORE INSERT ON REPRODUCCIONES
FOR EACH ROW
DECLARE v_estado USUARIOS.ESTADO_CUENTA%TYPE;
BEGIN
  SELECT u.ESTADO_CUENTA INTO v_estado FROM PERFILES p JOIN USUARIOS u ON u.ID_USUARIO = p.ID_USUARIO WHERE p.ID_PERFIL = :NEW.ID_PERFIL;
  IF v_estado <> 'ACTIVO' THEN RAISE_APPLICATION_ERROR(-20010, 'No se puede registrar reproducción en cuenta inactiva.'); END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PERFIL_MAX_PLAN
BEFORE INSERT ON PERFILES
FOR EACH ROW
DECLARE v_max NUMBER; v_actual NUMBER;
BEGIN
  SELECT pl.MAX_PERFILES INTO v_max FROM USUARIOS u JOIN PLANES pl ON pl.ID_PLAN = u.ID_PLAN WHERE u.ID_USUARIO = :NEW.ID_USUARIO;
  SELECT COUNT(*) INTO v_actual FROM PERFILES WHERE ID_USUARIO = :NEW.ID_USUARIO;
  IF v_actual >= v_max THEN RAISE_APPLICATION_ERROR(-20011, 'Se excede el máximo de perfiles del plan.'); END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CAL_MIN_REPROD
BEFORE INSERT ON CALIFICACIONES
FOR EACH ROW
DECLARE v_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existe FROM REPRODUCCIONES WHERE ID_PERFIL = :NEW.ID_PERFIL AND ID_CONTENIDO = :NEW.ID_CONTENIDO AND PORCENTAJE_AVANCE >= 50;
  IF v_existe = 0 THEN RAISE_APPLICATION_ERROR(-20012, 'Debe reproducir al menos 50% antes de calificar.'); END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAGOS_ACTIVAR_USUARIO
FOR INSERT ON PAGOS
COMPOUND TRIGGER
  TYPE t_ids IS TABLE OF PAGOS.ID_USUARIO%TYPE;
  g_ids t_ids := t_ids();
  AFTER EACH ROW IS
  BEGIN
    IF :NEW.ESTADO_PAGO = 'EXITOSO' THEN g_ids.EXTEND; g_ids(g_ids.COUNT) := :NEW.ID_USUARIO; END IF;
  END AFTER EACH ROW;
  AFTER STATEMENT IS
  BEGIN
    FOR i IN 1..g_ids.COUNT LOOP
      UPDATE USUARIOS SET ESTADO_CUENTA='ACTIVO', FECHA_ULTIMO_PAGO=SYSTIMESTAMP, FECHA_VENCIMIENTO=SYSTIMESTAMP + INTERVAL '30' DAY WHERE ID_USUARIO = g_ids(i);
    END LOOP;
  END AFTER STATEMENT;
END;
/


-- ============================================================================
-- PRUEBA_SP_REPORTE_CONSUMO
-- Bloque anónimo para probar el SYS_REFCURSOR en SQL Developer.
-- Active DBMS Output antes de ejecutar.
-- ============================================================================
DECLARE
  v_cursor SYS_REFCURSOR;
  v_perfil VARCHAR2(120);
  v_categoria VARCHAR2(80);
  v_reproducciones NUMBER;
  v_minutos NUMBER;
BEGIN
  SP_REPORTE_CONSUMO(
    p_id_usuario => 1,
    p_desde => DATE '2024-01-01',
    p_hasta => DATE '2026-12-31',
    p_cursor => v_cursor
  );

  LOOP
    FETCH v_cursor INTO v_perfil, v_categoria, v_reproducciones, v_minutos;
    EXIT WHEN v_cursor%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(
      'Perfil=' || v_perfil ||
      ' | Categoria=' || v_categoria ||
      ' | Reproducciones=' || v_reproducciones ||
      ' | Minutos=' || v_minutos
    );
  END LOOP;

  CLOSE v_cursor;
END;
/
