-- 06_indices_explain.sql
-- Núcleo 4: índices y análisis con EXPLAIN PLAN.
-- Ejecutar en SQL Developer con F5. Tomar capturas de BEFORE y AFTER.

SET SERVEROUTPUT ON;

PROMPT ================================================================
PROMPT 1) CONSULTA PESADA SOBRE REPRODUCCIONES - BEFORE INDEX
PROMPT ================================================================

BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_REP_PERFIL_FECHA';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1418 THEN -- ORA-01418: specified index does not exist
      RAISE;
    END IF;
END;
/

EXPLAIN PLAN SET STATEMENT_ID = 'REP_BEFORE' FOR
SELECT p.ID_PERFIL, p.NOMBRE, c.TITULO, r.FECHA_HORA_INICIO, r.PORCENTAJE_AVANCE
FROM REPRODUCCIONES r
JOIN PERFILES p ON p.ID_PERFIL = r.ID_PERFIL
JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
WHERE r.ID_PERFIL = 10
  AND r.FECHA_HORA_INICIO BETWEEN TO_TIMESTAMP('2024-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')
                              AND TO_TIMESTAMP('2026-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
ORDER BY r.FECHA_HORA_INICIO DESC;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'REP_BEFORE', 'BASIC +PREDICATE'));

PROMPT ================================================================
PROMPT 2) CREACIÓN DE ÍNDICE Y CONSULTA - AFTER INDEX
PROMPT ================================================================

CREATE INDEX IDX_REP_PERFIL_FECHA ON REPRODUCCIONES(ID_PERFIL, FECHA_HORA_INICIO);

EXPLAIN PLAN SET STATEMENT_ID = 'REP_AFTER' FOR
SELECT p.ID_PERFIL, p.NOMBRE, c.TITULO, r.FECHA_HORA_INICIO, r.PORCENTAJE_AVANCE
FROM REPRODUCCIONES r
JOIN PERFILES p ON p.ID_PERFIL = r.ID_PERFIL
JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
WHERE r.ID_PERFIL = 10
  AND r.FECHA_HORA_INICIO BETWEEN TO_TIMESTAMP('2024-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')
                              AND TO_TIMESTAMP('2026-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
ORDER BY r.FECHA_HORA_INICIO DESC;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'REP_AFTER', 'BASIC +PREDICATE'));

PROMPT ================================================================
PROMPT 3) ÍNDICE DE EMAIL PARA LOGIN / BÚSQUEDA CASE-INSENSITIVE
PROMPT ================================================================

-- La restricción UK_USUARIO_EMAIL garantiza unicidad del email desde V1.
-- Este índice funcional optimiza consultas LOWER(EMAIL), usadas por autenticación.
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_USUARIOS_EMAIL_LOWER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1418 THEN
      RAISE;
    END IF;
END;
/

EXPLAIN PLAN SET STATEMENT_ID = 'EMAIL_BEFORE' FOR
SELECT *
FROM USUARIOS
WHERE LOWER(EMAIL) = LOWER('usuario1@mail.com');

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'EMAIL_BEFORE', 'BASIC +PREDICATE'));

CREATE INDEX IDX_USUARIOS_EMAIL_LOWER ON USUARIOS(LOWER(EMAIL));

EXPLAIN PLAN SET STATEMENT_ID = 'EMAIL_AFTER' FOR
SELECT *
FROM USUARIOS
WHERE LOWER(EMAIL) = LOWER('usuario1@mail.com');

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'EMAIL_AFTER', 'BASIC +PREDICATE'));

PROMPT ================================================================
PROMPT 4) ÍNDICES ADICIONALES JUSTIFICADOS
PROMPT ================================================================

CREATE INDEX IDX_CONT_CAT_ANIO ON CONTENIDO(ID_CATEGORIA, ANIO_LANZAMIENTO);
CREATE INDEX IDX_PAGO_USUARIO_FECHA ON PAGOS(ID_USUARIO, FECHA_PAGO);
CREATE INDEX IDX_CONT_TITULO_UPPER ON CONTENIDO(UPPER(TITULO));

SELECT INDEX_NAME, TABLE_NAME
FROM USER_INDEXES
WHERE INDEX_NAME IN (
  'IDX_REP_PERFIL_FECHA',
  'IDX_USUARIOS_EMAIL_LOWER',
  'IDX_CONT_CAT_ANIO',
  'IDX_PAGO_USUARIO_FECHA',
  'IDX_CONT_TITULO_UPPER'
)
ORDER BY TABLE_NAME, INDEX_NAME;
