-- 06_indices_explain.sql
-- Núcleo 4: índices y análisis con EXPLAIN PLAN.
-- El objetivo es evidenciar el comportamiento antes y después de crear índices.

-- ==============================================================
-- 1) Consulta pesada sobre REPRODUCCIONES antes del índice
-- ============================================================== 
BEGIN
  EXECUTE IMMEDIATE 'DROP INDEX IDX_REP_PERFIL_FECHA';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/

EXPLAIN PLAN FOR
SELECT p.ID_PERFIL, p.NOMBRE, c.TITULO, r.FECHA_HORA_INICIO, r.PORCENTAJE_AVANCE
FROM REPRODUCCIONES r
JOIN PERFILES p ON p.ID_PERFIL = r.ID_PERFIL
JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
WHERE r.ID_PERFIL = 10
  AND r.FECHA_HORA_INICIO BETWEEN TO_TIMESTAMP('2024-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')
                              AND TO_TIMESTAMP('2026-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
ORDER BY r.FECHA_HORA_INICIO DESC;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX IDX_REP_PERFIL_FECHA ON REPRODUCCIONES(ID_PERFIL, FECHA_HORA_INICIO);

EXPLAIN PLAN FOR
SELECT p.ID_PERFIL, p.NOMBRE, c.TITULO, r.FECHA_HORA_INICIO, r.PORCENTAJE_AVANCE
FROM REPRODUCCIONES r
JOIN PERFILES p ON p.ID_PERFIL = r.ID_PERFIL
JOIN CONTENIDO c ON c.ID_CONTENIDO = r.ID_CONTENIDO
WHERE r.ID_PERFIL = 10
  AND r.FECHA_HORA_INICIO BETWEEN TO_TIMESTAMP('2024-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')
                              AND TO_TIMESTAMP('2026-12-31 23:59:59','YYYY-MM-DD HH24:MI:SS')
ORDER BY r.FECHA_HORA_INICIO DESC;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

-- ==============================================================
-- 2) Índices adicionales del proyecto
-- ============================================================== 
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONT_CAT_ANIO ON CONTENIDO(ID_CATEGORIA, ANIO_LANZAMIENTO)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_PAGO_USUARIO_FECHA ON PAGOS(ID_USUARIO, FECHA_PAGO)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONT_TITULO ON CONTENIDO(UPPER(TITULO))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_USUARIOS_EMAIL_LOWER ON USUARIOS(LOWER(EMAIL))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

EXPLAIN PLAN FOR
SELECT ID_USUARIO, NOMBRE, EMAIL
FROM USUARIOS
WHERE LOWER(EMAIL) = LOWER('usuario1@mail.com');
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
