-- 07_usuarios_roles.sql
-- Ejecutar como SYS/SYSTEM o usuario con privilegios para crear roles y usuarios.

CREATE PROFILE PERFIL_QUINDIOFLIX LIMIT SESSIONS_PER_USER 3 IDLE_TIME 20 FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;

CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_ANALISTA;
CREATE ROLE ROL_SOPORTE;
CREATE ROLE ROL_CONTENIDO;

GRANT SELECT, INSERT, UPDATE, DELETE ON PLANES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERFILES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPRODUCCIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CALIFICACIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAGOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FAVORITOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPORTES_CONTENIDO TO ROL_ADMIN;

GRANT EXECUTE ON SP_REPORTE_USUARIOS_VENCIDOS TO ROL_ADMIN;
GRANT EXECUTE ON SP_ACTUALIZAR_POPULARIDAD TO ROL_ADMIN;
GRANT EXECUTE ON SP_REGISTRAR_USUARIO TO ROL_ADMIN;
GRANT EXECUTE ON SP_CAMBIAR_PLAN TO ROL_ADMIN;
GRANT EXECUTE ON SP_REPORTE_CONSUMO TO ROL_ADMIN;
GRANT EXECUTE ON FN_CALCULAR_MONTO TO ROL_ADMIN;
GRANT EXECUTE ON FN_CONTENIDO_RECOMENDADO TO ROL_ADMIN;

GRANT SELECT ON PLANES TO ROL_ANALISTA;
GRANT SELECT ON USUARIOS TO ROL_ANALISTA;
GRANT SELECT ON PERFILES TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON REPRODUCCIONES TO ROL_ANALISTA;
GRANT SELECT ON CALIFICACIONES TO ROL_ANALISTA;
GRANT SELECT ON PAGOS TO ROL_ANALISTA;
GRANT SELECT ON MV_CONTENIDO_POPULAR TO ROL_ANALISTA;
GRANT SELECT ON MV_INGRESOS_MENSUALES TO ROL_ANALISTA;

GRANT SELECT ON USUARIOS TO ROL_SOPORTE;
GRANT SELECT ON PERFILES TO ROL_SOPORTE;
GRANT SELECT, INSERT, UPDATE ON PAGOS TO ROL_SOPORTE;
GRANT SELECT ON PLANES TO ROL_SOPORTE;
GRANT EXECUTE ON SP_CAMBIAR_PLAN TO ROL_SOPORTE;

GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_CONTENIDO;
GRANT SELECT ON REPRODUCCIONES TO ROL_CONTENIDO;
GRANT SELECT ON CALIFICACIONES TO ROL_CONTENIDO;

CREATE USER QF_ADMIN IDENTIFIED BY Admin_2026 PROFILE PERFIL_QUINDIOFLIX;
CREATE USER QF_ANALISTA IDENTIFIED BY Analista_2026 PROFILE PERFIL_QUINDIOFLIX;
CREATE USER QF_SOPORTE IDENTIFIED BY Soporte_2026 PROFILE PERFIL_QUINDIOFLIX;
CREATE USER QF_CONTENIDO IDENTIFIED BY Contenido_2026 PROFILE PERFIL_QUINDIOFLIX;

GRANT CREATE SESSION TO QF_ADMIN, QF_ANALISTA, QF_SOPORTE, QF_CONTENIDO;
GRANT ROL_ADMIN TO QF_ADMIN;
GRANT ROL_ANALISTA TO QF_ANALISTA;
GRANT ROL_SOPORTE TO QF_SOPORTE;
GRANT ROL_CONTENIDO TO QF_CONTENIDO;

-- Demostración de restricción:
-- Conectado como QF_ANALISTA, ejecutar:
-- INSERT INTO USUARIOS (...) VALUES (...);
-- Debe fallar con ORA-01031: privilegios insuficientes.
