-- 07_usuarios_roles.sql
-- Ejecutar como SYS/SYSTEM o usuario con privilegios para crear roles y usuarios.
-- Los objetos de la aplicación se referencian con prefijo QUINDIOFLIX_APP para evitar ORA-00942.

CREATE PROFILE PERFIL_QUINDIOFLIX LIMIT SESSIONS_PER_USER 3 IDLE_TIME 20 FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;

CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_ANALISTA;
CREATE ROLE ROL_SOPORTE;
CREATE ROLE ROL_CONTENIDO;

GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.PLANES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.USUARIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.PERFILES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.CONTENIDO TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.TEMPORADAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.EPISODIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.REPRODUCCIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.CALIFICACIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.PAGOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.FAVORITOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.REPORTES_CONTENIDO TO ROL_ADMIN;

GRANT EXECUTE ON QUINDIOFLIX_APP.SP_REPORTE_USUARIOS_VENCIDOS TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX_APP.SP_ACTUALIZAR_POPULARIDAD TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX_APP.SP_REGISTRAR_USUARIO TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX_APP.SP_CAMBIAR_PLAN TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX_APP.SP_REPORTE_CONSUMO TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX_APP.FN_CALCULAR_MONTO TO ROL_ADMIN;
GRANT EXECUTE ON QUINDIOFLIX_APP.FN_CONTENIDO_RECOMENDADO TO ROL_ADMIN;

GRANT SELECT ON QUINDIOFLIX_APP.PLANES TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.USUARIOS TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.PERFILES TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.CONTENIDO TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.REPRODUCCIONES TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.CALIFICACIONES TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.PAGOS TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.MV_CONTENIDO_POPULAR TO ROL_ANALISTA;
GRANT SELECT ON QUINDIOFLIX_APP.MV_INGRESOS_MENSUALES TO ROL_ANALISTA;

GRANT SELECT ON QUINDIOFLIX_APP.USUARIOS TO ROL_SOPORTE;
GRANT SELECT ON QUINDIOFLIX_APP.PERFILES TO ROL_SOPORTE;
GRANT SELECT, INSERT, UPDATE ON QUINDIOFLIX_APP.PAGOS TO ROL_SOPORTE;
GRANT SELECT ON QUINDIOFLIX_APP.PLANES TO ROL_SOPORTE;
GRANT EXECUTE ON QUINDIOFLIX_APP.SP_CAMBIAR_PLAN TO ROL_SOPORTE;

GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.CONTENIDO TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.TEMPORADAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.EPISODIOS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON QUINDIOFLIX_APP.GENEROS TO ROL_CONTENIDO;
GRANT SELECT ON QUINDIOFLIX_APP.REPRODUCCIONES TO ROL_CONTENIDO;
GRANT SELECT ON QUINDIOFLIX_APP.CALIFICACIONES TO ROL_CONTENIDO;

CREATE USER QF_ADMIN IDENTIFIED BY Admin_2026 PROFILE PERFIL_QUINDIOFLIX;
CREATE USER QF_ANALISTA IDENTIFIED BY Analista_2026 PROFILE PERFIL_QUINDIOFLIX;
CREATE USER QF_SOPORTE IDENTIFIED BY Soporte_2026 PROFILE PERFIL_QUINDIOFLIX;
CREATE USER QF_CONTENIDO IDENTIFIED BY Contenido_2026 PROFILE PERFIL_QUINDIOFLIX;

GRANT CREATE SESSION TO QF_ADMIN, QF_ANALISTA, QF_SOPORTE, QF_CONTENIDO;
GRANT ROL_ADMIN TO QF_ADMIN;
GRANT ROL_ANALISTA TO QF_ANALISTA;
GRANT ROL_SOPORTE TO QF_SOPORTE;
GRANT ROL_CONTENIDO TO QF_CONTENIDO;

-- Demostración de restricción:
-- Conectado como QF_ANALISTA, ejecutar:
-- INSERT INTO USUARIOS (...) VALUES (...);
-- Debe fallar con ORA-01031: privilegios insuficientes.
