-- ============================================================
-- 08_AJUSTES_FINALES_POST_CARGA.SQL
-- Proyecto QuindioFlix
-- Ejecutar conectado como QUINDIOFLIX_APP
-- Objetivo:
-- 1. Garantizar conteos mínimos exigidos por el proyecto.
-- 2. Refrescar y compilar vistas materializadas.
-- ============================================================

-- 1. Completar REPRODUCCIONES hasta mínimo 200
INSERT INTO REPRODUCCIONES (
    ID_PERFIL,
    ID_CONTENIDO,
    ID_EPISODIO,
    FECHA_HORA_INICIO,
    FECHA_HORA_FIN,
    DISPOSITIVO,
    PORCENTAJE_AVANCE
)
SELECT 
    ID_PERFIL,
    ID_CONTENIDO,
    NULL,
    SYSTIMESTAMP - NUMTODSINTERVAL(RN, 'DAY'),
    SYSTIMESTAMP - NUMTODSINTERVAL(RN, 'DAY') + NUMTODSINTERVAL(90, 'MINUTE'),
    'COMPUTADOR',
    95
FROM (
    SELECT 
        p.ID_PERFIL,
        c.ID_CONTENIDO,
        ROW_NUMBER() OVER (ORDER BY p.ID_PERFIL, c.ID_CONTENIDO) AS RN
    FROM PERFILES p
    JOIN USUARIOS u ON u.ID_USUARIO = p.ID_USUARIO
    CROSS JOIN CONTENIDO c
    WHERE u.ESTADO_CUENTA = 'ACTIVO'
)
WHERE RN <= (
    SELECT GREATEST(0, 200 - COUNT(*))
    FROM REPRODUCCIONES
);

-- 2. Completar CALIFICACIONES hasta mínimo 60
INSERT INTO CALIFICACIONES (
    ID_PERFIL,
    ID_CONTENIDO,
    ESTRELLAS,
    RESENA,
    FECHA_CALIFICACION
)
SELECT 
    ID_PERFIL,
    ID_CONTENIDO,
    5,
    'Calificación agregada para completar datos mínimos del proyecto.',
    SYSTIMESTAMP
FROM (
    SELECT DISTINCT
        r.ID_PERFIL,
        r.ID_CONTENIDO,
        ROW_NUMBER() OVER (ORDER BY r.ID_PERFIL, r.ID_CONTENIDO) AS RN
    FROM REPRODUCCIONES r
    WHERE r.PORCENTAJE_AVANCE >= 50
      AND NOT EXISTS (
          SELECT 1
          FROM CALIFICACIONES cal
          WHERE cal.ID_PERFIL = r.ID_PERFIL
            AND cal.ID_CONTENIDO = r.ID_CONTENIDO
      )
)
WHERE RN <= (
    SELECT GREATEST(0, 60 - COUNT(*))
    FROM CALIFICACIONES
);

-- 3. Completar FAVORITOS hasta mínimo 40
INSERT INTO FAVORITOS (
    ID_PERFIL,
    ID_CONTENIDO,
    FECHA_AGREGADO
)
SELECT 
    ID_PERFIL,
    ID_CONTENIDO,
    SYSTIMESTAMP
FROM (
    SELECT 
        p.ID_PERFIL,
        c.ID_CONTENIDO,
        ROW_NUMBER() OVER (ORDER BY p.ID_PERFIL, c.ID_CONTENIDO) AS RN
    FROM PERFILES p
    JOIN USUARIOS u ON u.ID_USUARIO = p.ID_USUARIO
    CROSS JOIN CONTENIDO c
    WHERE u.ESTADO_CUENTA = 'ACTIVO'
      AND NOT EXISTS (
          SELECT 1
          FROM FAVORITOS f
          WHERE f.ID_PERFIL = p.ID_PERFIL
            AND f.ID_CONTENIDO = c.ID_CONTENIDO
      )
)
WHERE RN <= (
    SELECT GREATEST(0, 40 - COUNT(*))
    FROM FAVORITOS
);

COMMIT;

-- 4. Refrescar vistas materializadas
BEGIN
    DBMS_MVIEW.REFRESH('MV_CONTENIDO_POPULAR', 'C');
    DBMS_MVIEW.REFRESH('MV_INGRESOS_MENSUALES', 'C');
END;
/

ALTER MATERIALIZED VIEW MV_CONTENIDO_POPULAR COMPILE;
ALTER MATERIALIZED VIEW MV_INGRESOS_MENSUALES COMPILE;

-- 5. Verificación de conteos mínimos
SELECT 'PLANES' tabla, COUNT(*) total FROM PLANES
UNION ALL SELECT 'USUARIOS', COUNT(*) FROM USUARIOS
UNION ALL SELECT 'PERFILES', COUNT(*) FROM PERFILES
UNION ALL SELECT 'CATEGORIAS', COUNT(*) FROM CATEGORIAS
UNION ALL SELECT 'GENEROS', COUNT(*) FROM GENEROS
UNION ALL SELECT 'CONTENIDO', COUNT(*) FROM CONTENIDO
UNION ALL SELECT 'TEMPORADAS', COUNT(*) FROM TEMPORADAS
UNION ALL SELECT 'EPISODIOS', COUNT(*) FROM EPISODIOS
UNION ALL SELECT 'REPRODUCCIONES', COUNT(*) FROM REPRODUCCIONES
UNION ALL SELECT 'CALIFICACIONES', COUNT(*) FROM CALIFICACIONES
UNION ALL SELECT 'PAGOS', COUNT(*) FROM PAGOS
UNION ALL SELECT 'FAVORITOS', COUNT(*) FROM FAVORITOS;

-- 6. Verificación de vistas materializadas
SELECT object_name, object_type, status
FROM user_objects
WHERE object_name IN ('MV_CONTENIDO_POPULAR', 'MV_INGRESOS_MENSUALES')
ORDER BY object_name, object_type;