-- V1__create_schema.sql
-- Modelo físico principal de QuindioFlix para Oracle.
-- Compatible con SQL Developer/Flyway. El script define claves primarias, foráneas,
-- checks, relaciones N:M y relaciones reflexivas.

CREATE TABLE PLANES (
  ID_PLAN NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
  PANTALLAS_SIMULTANEAS NUMBER(2) NOT NULL,
  CALIDAD VARCHAR2(10) NOT NULL,
  PRECIO_MENSUAL NUMBER(10,2) NOT NULL,
  MAX_PERFILES NUMBER(2) NOT NULL,
  ACTIVO CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT CK_PLAN_NOMBRE CHECK (NOMBRE IN ('BASICO','ESTANDAR','PREMIUM')),
  CONSTRAINT CK_PLAN_CALIDAD CHECK (CALIDAD IN ('SD','HD','4K')),
  CONSTRAINT CK_PLAN_PRECIO CHECK (PRECIO_MENSUAL > 0),
  CONSTRAINT CK_PLAN_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE DEPARTAMENTOS (
  ID_DEPARTAMENTO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(80) NOT NULL UNIQUE,
  ID_JEFE NUMBER(19,0) NULL
);

CREATE TABLE EMPLEADOS (
  ID_EMPLEADO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(120) NOT NULL,
  EMAIL VARCHAR2(150) NOT NULL,
  ID_DEPARTAMENTO NUMBER(19,0) NOT NULL,
  ID_SUPERVISOR NUMBER(19,0) NULL,
  CARGO VARCHAR2(80) NOT NULL,
  ACTIVO CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT CK_EMPLEADO_ACTIVO CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT FK_EMP_DEP FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
  CONSTRAINT FK_EMP_SUP FOREIGN KEY (ID_SUPERVISOR) REFERENCES EMPLEADOS(ID_EMPLEADO)
);
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT FK_DEP_JEFE FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADOS(ID_EMPLEADO);

CREATE TABLE USUARIOS (
  ID_USUARIO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(120) NOT NULL,
  EMAIL VARCHAR2(150) NOT NULL,
  TELEFONO VARCHAR2(30) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  CIUDAD VARCHAR2(80) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  ID_PLAN NUMBER(19,0) NOT NULL,
  ESTADO_CUENTA VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
  FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  FECHA_ULTIMO_PAGO TIMESTAMP NULL,
  FECHA_VENCIMIENTO TIMESTAMP NULL,
  ID_REFERIDO_POR NUMBER(19,0) NULL,
  ROL VARCHAR2(20) DEFAULT 'CLIENTE' NOT NULL,
  CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO_CUENTA IN ('ACTIVO','INACTIVO','SUSPENDIDO')),
  CONSTRAINT CK_USUARIO_ROL CHECK (ROL IN ('CLIENTE','MODERADOR','CONTENIDO','ADMIN')),
  CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL),
  CONSTRAINT FK_USU_PLAN FOREIGN KEY (ID_PLAN) REFERENCES PLANES(ID_PLAN),
  CONSTRAINT FK_USU_REFERIDO FOREIGN KEY (ID_REFERIDO_POR) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PERFILES (
  ID_PERFIL NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_USUARIO NUMBER(19,0) NOT NULL,
  NOMBRE VARCHAR2(60) NOT NULL,
  AVATAR VARCHAR2(255),
  TIPO_PERFIL VARCHAR2(20) NOT NULL,
  CONSTRAINT CK_PERFIL_TIPO CHECK (TIPO_PERFIL IN ('ADULTO','INFANTIL')),
  CONSTRAINT FK_PERFIL_USU FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT UK_PERFIL_USUARIO_NOMBRE UNIQUE (ID_USUARIO, NOMBRE)
);

CREATE TABLE CATEGORIAS (
  ID_CATEGORIA NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(50) NOT NULL UNIQUE,
  TIPO_CONTENIDO VARCHAR2(20) NOT NULL,
  CONSTRAINT CK_CAT_TIPO CHECK (TIPO_CONTENIDO IN ('PELICULA','SERIE','DOCUMENTAL','MUSICA','PODCAST'))
);

CREATE TABLE GENEROS (
  ID_GENERO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOMBRE VARCHAR2(60) NOT NULL UNIQUE
);

CREATE TABLE CONTENIDO (
  ID_CONTENIDO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_CATEGORIA NUMBER(19,0) NOT NULL,
  TITULO VARCHAR2(200) NOT NULL,
  ANIO_LANZAMIENTO NUMBER(4) NOT NULL,
  DURACION_MINUTOS NUMBER(5) NOT NULL,
  SINOPSIS VARCHAR2(2000),
  CLASIFICACION_EDAD VARCHAR2(20) NOT NULL,
  FECHA_AGREGADO DATE DEFAULT SYSDATE NOT NULL,
  ORIGINAL_QUINDIOFLIX CHAR(1) DEFAULT 'N' NOT NULL,
  ID_EMPLEADO_RESPONSABLE NUMBER(19,0) NOT NULL,
  POPULARIDAD NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT CK_CONT_CLASIF CHECK (CLASIFICACION_EDAD IN ('TP','MAS_7','MAS_13','MAS_16','MAS_18')),
  CONSTRAINT CK_CONT_ORIGINAL CHECK (ORIGINAL_QUINDIOFLIX IN ('S','N')),
  CONSTRAINT CK_CONT_DURACION CHECK (DURACION_MINUTOS > 0),
  CONSTRAINT FK_CONT_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
  CONSTRAINT FK_CONT_EMP FOREIGN KEY (ID_EMPLEADO_RESPONSABLE) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE CONTENIDO_GENERO (
  ID_CONTENIDO NUMBER(19,0) NOT NULL,
  ID_GENERO NUMBER(19,0) NOT NULL,
  CONSTRAINT PK_CONT_GEN PRIMARY KEY (ID_CONTENIDO, ID_GENERO),
  CONSTRAINT FK_CG_CONT FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT FK_CG_GEN FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID_GENERO)
);

CREATE TABLE TEMPORADAS (
  ID_TEMPORADA NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_CONTENIDO NUMBER(19,0) NOT NULL,
  NUMERO_TEMPORADA NUMBER(3) NOT NULL,
  TITULO VARCHAR2(160) NOT NULL,
  FECHA_LANZAMIENTO DATE,
  CONSTRAINT FK_TEMP_CONT FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT UK_TEMPORADA_CONTENIDO_NUM UNIQUE (ID_CONTENIDO, NUMERO_TEMPORADA)
);

CREATE TABLE EPISODIOS (
  ID_EPISODIO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_TEMPORADA NUMBER(19,0) NOT NULL,
  NUMERO_EPISODIO NUMBER(4) NOT NULL,
  TITULO VARCHAR2(200) NOT NULL,
  DURACION_MINUTOS NUMBER(5) NOT NULL,
  SINOPSIS VARCHAR2(2000),
  CONSTRAINT FK_EP_TEMP FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADAS(ID_TEMPORADA),
  CONSTRAINT UK_EP_TEMP_NUM UNIQUE (ID_TEMPORADA, NUMERO_EPISODIO),
  CONSTRAINT CK_EP_DUR CHECK (DURACION_MINUTOS > 0)
);

CREATE TABLE CONTENIDO_RELACIONADO (
  ID_RELACION NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_CONTENIDO_ORIGEN NUMBER(19,0) NOT NULL,
  ID_CONTENIDO_DESTINO NUMBER(19,0) NOT NULL,
  TIPO_RELACION VARCHAR2(60) NOT NULL,
  DESCRIPCION VARCHAR2(500),
  CONSTRAINT FK_CR_ORIGEN FOREIGN KEY (ID_CONTENIDO_ORIGEN) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT FK_CR_DESTINO FOREIGN KEY (ID_CONTENIDO_DESTINO) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT CK_CR_DIF CHECK (ID_CONTENIDO_ORIGEN <> ID_CONTENIDO_DESTINO)
);

CREATE TABLE REPRODUCCIONES (
  ID_REPRODUCCION NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_PERFIL NUMBER(19,0) NOT NULL,
  ID_CONTENIDO NUMBER(19,0) NOT NULL,
  ID_EPISODIO NUMBER(19,0) NULL,
  FECHA_HORA_INICIO TIMESTAMP NOT NULL,
  FECHA_HORA_FIN TIMESTAMP NULL,
  DISPOSITIVO VARCHAR2(20) NOT NULL,
  PORCENTAJE_AVANCE NUMBER(3) NOT NULL,
  CONSTRAINT CK_REP_DISP CHECK (DISPOSITIVO IN ('CELULAR','TABLET','TV','COMPUTADOR')),
  CONSTRAINT CK_REP_AVANCE CHECK (PORCENTAJE_AVANCE BETWEEN 0 AND 100),
  CONSTRAINT CK_REP_FECHAS CHECK (FECHA_HORA_FIN IS NULL OR FECHA_HORA_FIN >= FECHA_HORA_INICIO),
  CONSTRAINT FK_REP_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES(ID_PERFIL),
  CONSTRAINT FK_REP_CONT FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT FK_REP_EP FOREIGN KEY (ID_EPISODIO) REFERENCES EPISODIOS(ID_EPISODIO)
);

CREATE TABLE CALIFICACIONES (
  ID_CALIFICACION NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_PERFIL NUMBER(19,0) NOT NULL,
  ID_CONTENIDO NUMBER(19,0) NOT NULL,
  ESTRELLAS NUMBER(1) NOT NULL,
  RESENA VARCHAR2(1000),
  FECHA_CALIFICACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_CAL_EST CHECK (ESTRELLAS BETWEEN 1 AND 5),
  CONSTRAINT FK_CAL_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES(ID_PERFIL),
  CONSTRAINT FK_CAL_CONT FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT UK_CALIFICACION_PERFIL_CONT UNIQUE (ID_PERFIL, ID_CONTENIDO)
);

CREATE TABLE FAVORITOS (
  ID_FAVORITO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_PERFIL NUMBER(19,0) NOT NULL,
  ID_CONTENIDO NUMBER(19,0) NOT NULL,
  FECHA_AGREGADO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_FAV_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES(ID_PERFIL),
  CONSTRAINT FK_FAV_CONT FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT UK_FAVORITO_PERFIL_CONT UNIQUE (ID_PERFIL, ID_CONTENIDO)
);

CREATE TABLE PAGOS (
  ID_PAGO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_USUARIO NUMBER(19,0) NOT NULL,
  FECHA_PAGO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  MONTO NUMBER(10,2) NOT NULL,
  METODO_PAGO VARCHAR2(30) NOT NULL,
  ESTADO_PAGO VARCHAR2(20) NOT NULL,
  REFERENCIA VARCHAR2(120),
  DESCUENTO_APLICADO NUMBER(10,2) DEFAULT 0 NOT NULL,
  CONSTRAINT CK_PAGO_METODO CHECK (METODO_PAGO IN ('TARJETA_CREDITO','TARJETA_DEBITO','PSE','NEQUI','DAVIPLATA')),
  CONSTRAINT CK_PAGO_ESTADO CHECK (ESTADO_PAGO IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')),
  CONSTRAINT CK_PAGO_MONTO CHECK (MONTO > 0),
  CONSTRAINT FK_PAGO_USU FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE REPORTES_CONTENIDO (
  ID_REPORTE NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_USUARIO_REPORTA NUMBER(19,0) NOT NULL,
  ID_CONTENIDO NUMBER(19,0) NOT NULL,
  DESCRIPCION VARCHAR2(1000) NOT NULL,
  FECHA_REPORTE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
  ID_MODERADOR NUMBER(19,0) NULL,
  FECHA_RESOLUCION TIMESTAMP NULL,
  COMENTARIO_RESOLUCION VARCHAR2(1000),
  CONSTRAINT CK_REPORTE_ESTADO CHECK (ESTADO IN ('PENDIENTE','RESUELTO','RECHAZADO')),
  CONSTRAINT FK_REP_USU_REPORTA FOREIGN KEY (ID_USUARIO_REPORTA) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT FK_REP_CONTENIDO FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
  CONSTRAINT FK_REP_MOD FOREIGN KEY (ID_MODERADOR) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE CAMBIOS_PLAN (
  ID_CAMBIO NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_USUARIO NUMBER(19,0) NOT NULL,
  ID_PLAN_ANTERIOR NUMBER(19,0) NOT NULL,
  ID_PLAN_NUEVO NUMBER(19,0) NOT NULL,
  FECHA_CAMBIO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  MOTIVO VARCHAR2(200),
  CONSTRAINT FK_CP_USU FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT FK_CP_PLAN_ANT FOREIGN KEY (ID_PLAN_ANTERIOR) REFERENCES PLANES(ID_PLAN),
  CONSTRAINT FK_CP_PLAN_NUE FOREIGN KEY (ID_PLAN_NUEVO) REFERENCES PLANES(ID_PLAN)
);

COMMENT ON TABLE REPRODUCCIONES IS 'Historial de consumo de contenido por perfil. Tabla candidata a fragmentación/partición por fecha.';
COMMENT ON COLUMN USUARIOS.ID_REFERIDO_POR IS 'Relación reflexiva: usuario que refirió al usuario actual.';
COMMENT ON TABLE CONTENIDO_RELACIONADO IS 'Relación reflexiva entre contenidos: secuela, precuela, remake, spin-off, versión extendida, etc.';
