-- V3__indexes.sql
-- Índices usados por búsquedas frecuentes e historial de consumo.
-- La unicidad de USUARIOS.EMAIL se define en V1 con UK_USUARIO_EMAIL.
-- Este índice funcional optimiza búsquedas/login case-insensitive por correo.
CREATE INDEX IDX_USUARIOS_EMAIL_LOWER ON USUARIOS(LOWER(EMAIL));
CREATE INDEX IDX_REP_PERFIL_FECHA ON REPRODUCCIONES(ID_PERFIL, FECHA_HORA_INICIO);
CREATE INDEX IDX_CONT_CAT_ANIO ON CONTENIDO(ID_CATEGORIA, ANIO_LANZAMIENTO);
CREATE INDEX IDX_PAGO_USUARIO_FECHA ON PAGOS(ID_USUARIO, FECHA_PAGO);
CREATE INDEX IDX_CONT_TITULO_UPPER ON CONTENIDO(UPPER(TITULO));
